apiVersion: v1
kind: Service
metadata:
  annotations:
    redacted/domain-name: "skeefree-%environment%.redacted"
  name: skeefree
  labels:
    service: skeefree
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: skeefree
  type: LoadBalancer
